---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-aem-package"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: get docker host ip
      become: yes
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  roles:
    - {
      role: "aem_design.aem_license",
      aem_license_key: "{{ service_aem_license_key }}",
      aem_license_name: "{{ service_aem_license_name }}",
      aem_port: "5502",
      aem_host: "{{ dockerhost_ip.stdout }}",
      debug_hide: false
    }
    - {
      role: "{{ role_name }}",
      aem_port: "5502",
      aem_host: "{{ dockerhost_ip.stdout }}",
      adobe_cloud_username: "{{ service_adobe_cloud_username }}",
      adobe_cloud_password: "{{ service_adobe_cloud_password }}",
      debug_hide: false
      package_files:
        - {
          package_source: "adobecloud",
          simple_name: "vanityurls",
          file_name: 'vanityurls-components-1.0.2.zip',
          version: '1.0.2',
          group_name: 'Adobe',
          package_name: 'vanityurls-components',
          requires_restart: false,
          requires_admin: false,
          package_url: "https://www.adobeaemcloud.com/content/companies/public/adobe/packages/cq600/component/vanityurls-components/jcr%3acontent/package/file.res/vanityurls-components-1.0.2.zip"
        }
        - {
          package_source: "maven",
          simple_name: "acs twitter",
          file_name: 'com.adobe.acs.bundles.twitter4j-content-1.0.0.zip',
          version: '1.0.0',
          group_name: 'day_internal/consulting',
          package_name: 'com.adobe.acs.bundles.twitter4j-content',
          requires_restart: false,
          requires_admin: false,
          package_url: 'https://github.com/Adobe-Consulting-Services/com.adobe.acs.bundles.twitter4j/releases/download/com.adobe.acs.bundles.twitter4j-1.0.0/com.adobe.acs.bundles.twitter4j-content-1.0.0.zip'
        }
    }
